//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartParkingApplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Image
    {
        public int ImageID { get; set; }
        public string LinkImageIN { get; set; }
        public string LinkImageOut { get; set; }
        public Nullable<int> TransactionID { get; set; }
    
        public virtual Transaction Transaction { get; set; }
    }
}
