//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartParkingApplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MonthlyIncomeStatement
    {
        public int MonthlyIncomeStatementID { get; set; }
        public Nullable<int> MonthlyTicketID { get; set; }
        public Nullable<int> TotalPrice { get; set; }
    
        public virtual MonthlyTicket MonthlyTicket { get; set; }
    }
}
